# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6da0d74d12bfff83ad82c5f9ee5f43f8b2a04bb793e9da7b748f8de3419789d2abc86ae665fcb466ec8166d28a0d8c2580665e7b47a3104fb69c1967f82eec93

test:
  secret_key_base: 83aff6c4be4d485ba9a07a3ed8dc4bc718101de1377b1c0f8dd8c0ace57e367f18c1ccf714782f5966c6b692230b6b7bc552bc6717afa285a9a785addd216411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
